apiVersion: apps/v1
kind: Deployment
metadata:
  name: ylochman-hw
spec:
  selector:
    matchLabels:
      run: ylochman-hw
  replicas: 3
  template:
    metadata:
      labels:
        run: ylochman-hw
    spec:
      containers:
      - name: ylochman-hw
        image: ylochman/apps-cloud-infra
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "250m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        readinessProbe:
          httpGet:
            path: /healthy
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthy
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3