apiVersion: v1
kind: Service
metadata:
  name: ylochman-hw-service
  labels:
    run: ylochman-hw
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: ylochman-hw
